version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.23
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: 4466
        databases:
          default:
            connector: mongo
            uri: mongodb://${PRISMA_MONGO_USER}:${PRISMA_MONGO_PASSWORD}@mongo
  mongo:
    image: mongo:4.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${PRISMA_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${PRISMA_MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo:/var/lib/mongo
volumes:
  mongo:
