backend:
  name: git-gateway
  branch: blog
  publish_mode: editorial_workflow

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections: # A list of collections (content types) the CMS can edit
  - name: "blog" # used in site URLs - /admin/{collection}/{slug}/edit
    label: "Blog"
    folder: "content/blog" # Path to folder where the documents are stored
    create: true # Ability for users to create new documents in this collection
    slug: "{{slug}}" # File name template
    fields: # The fields for each document correspond to its front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Post Summary", name: "description", widget: "text" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Content", name: "body", widget: "markdown" }
  